import {test,expect} from "@playwright/test";
async function mockPads(page,pads=[]){await page.addInitScript(initial=>{let current=initial;Object.defineProperty(navigator,"getGamepads",{value:()=>current});window.__setPads=p=>current=p;},pads)}
async function open(page,url="/?gamepadMock=1#survey"){await page.goto(url);await expect(page.locator("#gamepadPanel")).toBeAttached();await page.waitForFunction(()=>Boolean(window.gamepadController));await page.evaluate(()=>{gamepadPanel.hidden=false;gamepadPanel.open=true})}
async function openSimulator(page){await page.evaluate(()=>{const el=document.querySelector("#gpSimulator");if(el)el.open=true})}
async function activate(page,selector){await page.evaluate(s=>document.querySelector(s)?.click(),selector)}
test("no controller is safe and exposes no aircraft controls",async({page})=>{await mockPads(page);await open(page);await expect(page.locator("#gpContent")).toContainText("Not detected");await expect(page.locator("#gamepadPanel")).toContainText("No aircraft commands are being transmitted");await expect(page.locator("#gamepadPanel button",{hasText:/Arm|Takeoff/})).toHaveCount(0)});
test("generic browser controller and likely DualSense are detected",async({page})=>{const pad={index:0,id:"Generic standard controller",mapping:"standard",axes:[.4,0,0,0],buttons:Array.from({length:18},()=>({pressed:false,touched:false,value:0})),timestamp:performance.now()};await mockPads(page,[pad]);await open(page,"/#survey");await expect(page.locator("#gpContent")).toContainText("Generic standard controller");await expect(page.locator("#gpContent")).not.toContainText("DualSense候補")});
test("simulator connects, moves, dead-man releases and disconnect zeros",async({page})=>{await mockPads(page);await open(page);await page.evaluate(()=>{window.gamepadController.switchProvider(window.gamepadController.mock);window.gamepadController.mock.connect()});await page.waitForFunction(()=>Boolean(window.gamepadController.calibration));await expect(page.locator("#gpContent")).toContainText("Simulated DualSense Controller");await page.evaluate(()=>{const c=window.gamepadController;c.calibration.validationState="valid";c.mock.setAxis(0,.8);c.mock.setButton(4,1);c.mock.setButton(4,0)});await expect(page.locator(".gp-gate")).toContainText("deadman-released");await page.evaluate(()=>window.gamepadController.mock.disconnect());await expect(page.locator(".gp-gate")).toContainText("controller-disconnected")});
test("narrow layout has no horizontal overflow or overlapping indicators",async({page})=>{await page.setViewportSize({width:390,height:844});await mockPads(page);await open(page);await activate(page,"#gpMockConnect");const result=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth-document.documentElement.clientWidth,overlap:(()=>{const a=document.querySelector('.gp-sim')?.getBoundingClientRect(),b=document.querySelector('.gp-status strong')?.getBoundingClientRect();return a&&b&&!(a.right<=b.left||b.right<=a.left||a.bottom<=b.top||b.bottom<=a.top)})()}));expect(result.overflow).toBeLessThanOrEqual(1);expect(result.overlap).toBeFalsy()});
test("gamepad interaction makes no command API request",async({page})=>{const requests=[];page.on("request",r=>{if(/api\/.+(command|arm|takeoff|manual)/i.test(r.url()))requests.push(r.url())});await mockPads(page);await open(page);await activate(page,"#gpMockConnect");await page.evaluate(()=>gamepadController.mock.setAxis(1,1));expect(requests).toEqual([])});
