// End-to-end test of the whole offline pipeline, from an NMEA file on disk to
// a verdict, through the project's EXISTING parser.
//
// The fixtures are SYNTHETIC and named so — see
// tests/fixtures/qz1-water-level/*.SYNTHETIC.*, generated by
// experiments/qz1-water-level/scripts/make-synthetic-log.mjs from a noise
// model. What this file proves is that the code does what it claims: that a
// step buried in noise comes out FAIL and a step well above the noise comes
// out PASS, that the two paths through the pipeline agree, and that nothing
// is fabricated on the way. It proves NOTHING about QZ1 hardware. Only the
// physical experiment in docs/qz1-floating-water-level/EXPERIMENT.md can do
// that.

import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

import { parseNmeaSession } from "../../js/gnss/nmea-parser.js";
import { observationsToSamples } from "../../js/qz1-water-level/experiment-samples.js";
import { normalizeExperimentConfig } from "../../js/qz1-water-level/experiment-config.js";
import { VERDICTS, analyzeExperiment } from "../../js/qz1-water-level/displacement-analysis.js";
import { experimentToCsv, marksFromLabelledSamples, parseExperimentCsv } from "../../js/qz1-water-level/experiment-csv.js";
import { renderTextReport } from "../../js/qz1-water-level/experiment-report.js";

const FIXTURES = resolve(dirname(fileURLToPath(import.meta.url)), "../fixtures/qz1-water-level");

function loadFixture(name) {
  const text = readFileSync(resolve(FIXTURES, `${name}.SYNTHETIC.nmea`), "utf8");
  const marksFile = JSON.parse(readFileSync(resolve(FIXTURES, `${name}.SYNTHETIC.marks.json`), "utf8"));
  const configFile = JSON.parse(readFileSync(resolve(FIXTURES, `${name}.SYNTHETIC.config.json`), "utf8"));
  const { config, errors } = normalizeExperimentConfig(configFile);
  assert.deepEqual(errors, [], "the fixture's own config must be valid");
  const parsed = parseNmeaSession(text, { receiver: { id: "qz1", role: "qz1" }, sessionId: name });
  return { config, marks: marksFile.marks, samples: observationsToSamples(parsed.observations), parsed, marksFile };
}

test("every committed fixture is labelled synthetic in its own contents", () => {
  for (const name of ["noisy-40mm", "quiet-3mm"]) {
    const { marksFile } = loadFixture(name);
    assert.equal(marksFile.synthetic, true);
    assert.ok(marksFile.warning.includes("SYNTHETIC"));
    const nmea = readFileSync(resolve(FIXTURES, `${name}.SYNTHETIC.nmea`), "utf8");
    assert.ok(nmea.startsWith("# SYNTHETIC DATA"),
      "a reader who opens the log with no context must see immediately that it is not a measurement");
  }
});

test("the shared parser reads the fixture: no second NMEA implementation is involved", () => {
  const { parsed, samples } = loadFixture("quiet-3mm");
  assert.equal(parsed.session.parserSummary.observationCount, 245);
  assert.equal(parsed.session.parserSummary.invalidChecksums, 0, "the generator writes valid checksums");
  assert.equal(samples.length, 245);
  assert.ok(samples.every((sample) => Number.isFinite(sample.altitudeMm)));
  assert.ok(samples.every((sample) => Number.isFinite(sample.timestampUtcMs)),
    "RMC/ZDA supply the date, so the offline path has real GNSS UTC");
});

test("a quiet signal resolves the large steps", () => {
  const { config, marks, samples } = loadFixture("quiet-3mm");
  const analysis = analyzeExperiment({ samples, marks, config });
  assert.equal(analysis.ok, true);
  assert.equal(analysis.verdicts[100], VERDICTS.PASS, "a 100 mm step against 3 mm of noise");
  assert.equal(analysis.verdicts[30], VERDICTS.PASS);
});

test("a 40 mm-noise signal does NOT resolve a 10 mm step, and says so", () => {
  const { config, marks, samples } = loadFixture("noisy-40mm");
  const analysis = analyzeExperiment({ samples, marks, config });
  assert.equal(analysis.ok, true, "a negative result is a successful analysis");
  assert.notEqual(analysis.verdicts[10], VERDICTS.PASS,
    "10 mm must not be claimed as resolved when the noise is four times larger");
});

test("errors are computed against the reference, not against the fitted line", () => {
  const { config, marks, samples } = loadFixture("quiet-3mm");
  const analysis = analyzeExperiment({ samples, marks, config });
  for (const level of analysis.levels) {
    if (level.deltaGnssMm === null) continue;
    assert.ok(Math.abs(level.errorMm - (level.deltaGnssMm - level.deltaReferenceMm)) < 1e-9,
      "error is exactly (estimate − truth); no fitting, no scaling, no offset");
  }
});

test("the same data through the CSV path reaches the same verdicts", () => {
  const { config, marks, samples } = loadFixture("quiet-3mm");
  const direct = analyzeExperiment({ samples, marks, config });

  // Label, serialize, read back, rebuild the marks from the labels alone.
  const labelled = samples.map((sample) => {
    const mark = marks.find((candidate) =>
      sample.timestampUtcMs >= candidate.startMs && sample.timestampUtcMs < candidate.endMs);
    return mark
      ? { ...sample, referenceHeightMm: mark.referenceHeightMm, stepIndex: mark.stepIndex, visitIndex: mark.visitIndex, direction: mark.direction }
      : sample;
  });
  const csv = experimentToCsv(labelled, { experimentId: config.experimentId, stage: config.stage });
  const reread = parseExperimentCsv(csv);
  assert.deepEqual(reread.errors, []);

  const viaCsv = analyzeExperiment({
    samples: reread.samples,
    // The settle window was already applied when the labels were written, so
    // the reconstructed marks must not re-apply it.
    marks: marksFromLabelledSamples(reread.samples).map((mark) => ({ ...mark, settleSeconds: 0 })),
    config
  });
  assert.equal(viaCsv.ok, true);
  assert.deepEqual(viaCsv.verdicts, direct.verdicts,
    "an archived CSV must reproduce the verdicts of the live analysis");
});

test("repositioning samples land in no level and are counted, not silently dropped", () => {
  const { config, marks, samples } = loadFixture("quiet-3mm");
  const analysis = analyzeExperiment({ samples, marks, config });
  // 7 steps × 5 s of gap in the generator.
  assert.equal(analysis.unassignedSampleCount, 35);
  assert.equal(analysis.settlingSampleCount, 35, "7 steps × 5 s of settling");
  const accounted = analysis.levels.reduce((total, level) => total + level.rawSampleCount, 0)
    + analysis.unassignedSampleCount + analysis.settlingSampleCount + analysis.undatableSampleCount;
  assert.equal(accounted, samples.length, "every sample is accounted for somewhere");
});

test("a filter chain changes the numbers and is reported alongside them", () => {
  const { config, marks, samples } = loadFixture("noisy-40mm");
  const unfiltered = analyzeExperiment({ samples, marks, config, filterChain: [] });
  const filtered = analyzeExperiment({ samples, marks, config, filterChain: "standard-quality-gate" });

  assert.deepEqual(unfiltered.filterChain, []);
  assert.ok(filtered.filterChain.length > 0);
  const report = renderTextReport(filtered);
  assert.ok(report.includes("mad-outlier"), "the exact chain appears in the report");
  assert.ok(report.includes("after filtering"), "and so does what it removed");
});

test("raw statistics are identical whatever the filter chain is", () => {
  // The raw column must be a fixed point of reference. If filtering could
  // move it, there would be no way to see what the filter did.
  const { config, marks, samples } = loadFixture("noisy-40mm");
  const a = analyzeExperiment({ samples, marks, config, filterChain: [] });
  const b = analyzeExperiment({ samples, marks, config, filterChain: "quality-gate-then-median-15" });
  for (let index = 0; index < a.levels.length; index += 1) {
    assert.equal(a.levels[index].raw.meanMm, b.levels[index].raw.meanMm);
    assert.equal(a.levels[index].raw.count, b.levels[index].raw.count);
  }
});

test("the fixture's own telemetry coverage is reported honestly", () => {
  const { config, marks, samples } = loadFixture("quiet-3mm");
  const analysis = analyzeExperiment({ samples, marks, config });
  // The generator emits GSA, so VDOP/PDOP are present — as they are in the
  // project's real QZ1 log (data/samples/qz1-dorm-walk-20260706.txt).
  assert.equal(analysis.telemetryCoverage.vdop.present, 245);
  // The generator emits no GQGSV, so QZSS visibility was genuinely never
  // reported. It is listed as missing rather than shown as "0 visible" --
  // Number(null) === 0 would have turned "the receiver never said" into a
  // measured zero.
  assert.deepEqual(analysis.alwaysMissingFields, ["qzssVisible"]);
  assert.equal(analysis.telemetryCoverage.qzssVisible.present, 0);
  assert.ok(analysis.warnings.some((warning) => warning.includes("qzssVisible")),
    "and the report names it rather than leaving a silently empty column");
});
